'use strict';
const SHOP_ITEMS = [
  { id:'hat_tophat',     cat:'clothing', slot:'hat',     label:'Top Hat',        emoji:'🎩', price:40,  rarity:'uncommon',  desc:'A dapper silk top hat' },
  { id:'hat_party',      cat:'clothing', slot:'hat',     label:'Party Hat',      emoji:'🎉', price:15,  rarity:'common',    desc:'For every occasion' },
  { id:'hat_crown',      cat:'clothing', slot:'hat',     label:'Golden Crown',   emoji:'👑', price:150, rarity:'rare',      desc:'Royalty only' },
  { id:'hat_witch',      cat:'clothing', slot:'hat',     label:'Witch Hat',      emoji:'🧙', price:55,  rarity:'uncommon',  desc:'Mysterious and tall' },
  { id:'hat_cowboy',     cat:'clothing', slot:'hat',     label:'Cowboy Hat',     emoji:'🤠', price:35,  rarity:'common',    desc:'Yeehaw pardner' },
  { id:'hat_santa',      cat:'clothing', slot:'hat',     label:'Santa Hat',      emoji:'🎅', price:30,  rarity:'common',    desc:'Ho ho ho!' },
  { id:'hat_graduation', cat:'clothing', slot:'hat',     label:'Grad Cap',       emoji:'🎓', price:45,  rarity:'uncommon',  desc:'You did it!' },
  { id:'hat_astro',      cat:'clothing', slot:'hat',     label:'Astronaut Helm', emoji:'👨‍🚀', price:120, rarity:'rare',     desc:'Ready for liftoff' },
  { id:'hat_crown_j',    cat:'clothing', slot:'hat',     label:'Jester Crown',   emoji:'🃏', price:80,  rarity:'rare',      desc:"The fool's finest" },
  { id:'shirt_rainbow',  cat:'clothing', slot:'shirt',   label:'Rainbow Tee',    emoji:'🌈', price:25,  rarity:'common',    desc:'All the colors!' },
  { id:'shirt_star',     cat:'clothing', slot:'shirt',   label:'Star Shirt',     emoji:'⭐', price:30,  rarity:'common',    desc:"You're a star" },
  { id:'shirt_fish',     cat:'clothing', slot:'shirt',   label:'Fish Tee',       emoji:'🐟', price:20,  rarity:'common',    desc:'For the seafood fan' },
  { id:'shirt_flower',   cat:'clothing', slot:'shirt',   label:'Flower Blouse',  emoji:'🌸', price:35,  rarity:'common',    desc:'Spring vibes' },
  { id:'shirt_fire',     cat:'clothing', slot:'shirt',   label:'Fire Hoodie',    emoji:'🔥', price:50,  rarity:'uncommon',  desc:'Too hot to handle' },
  { id:'shirt_moon',     cat:'clothing', slot:'shirt',   label:'Moon Sweater',   emoji:'🌙', price:45,  rarity:'uncommon',  desc:'Soft & cozy' },
  { id:'shirt_dino',     cat:'clothing', slot:'shirt',   label:'Dino Shirt',     emoji:'🦕', price:40,  rarity:'uncommon',  desc:'Rawr!' },
  { id:'shirt_pizza',    cat:'clothing', slot:'shirt',   label:'Pizza Tee',      emoji:'🍕', price:22,  rarity:'common',    desc:'Always hungry' },
  { id:'shirt_galaxy',   cat:'clothing', slot:'shirt',   label:'Galaxy Jacket',  emoji:'🌌', price:100, rarity:'rare',      desc:'Wear the cosmos' },
  { id:'shirt_tuxedo',   cat:'clothing', slot:'shirt',   label:'Tuxedo',         emoji:'🤵', price:120, rarity:'rare',      desc:'Fancy occasion required' },
  { id:'pat_spots',      cat:'clothing', slot:'pattern', label:'Spotted',        emoji:'🔴', price:50,  rarity:'uncommon',  desc:'Dalmatian vibes',   patternKey:'spots'   },
  { id:'pat_stripes',    cat:'clothing', slot:'pattern', label:'Tiger Stripes',  emoji:'🐯', price:60,  rarity:'uncommon',  desc:'Wild side',         patternKey:'stripes' },
  { id:'pat_stars',      cat:'clothing', slot:'pattern', label:'Starry',         emoji:'✨', price:80,  rarity:'rare',      desc:'You shine bright',  patternKey:'stars'   },
  { id:'pat_camo',       cat:'clothing', slot:'pattern', label:'Camo',           emoji:'🌿', price:45,  rarity:'uncommon',  desc:'Now you see me',    patternKey:'camo'    },
  { id:'pat_galaxy',     cat:'clothing', slot:'pattern', label:'Galaxy Coat',    emoji:'🌌', price:150, rarity:'legendary', desc:'Cosmic beauty',     patternKey:'galaxy'  },
  { id:'pat_glitter',    cat:'clothing', slot:'pattern', label:'Glitter',        emoji:'💫', price:90,  rarity:'rare',      desc:'Shine on',          patternKey:'glitter' },
  { id:'worm',      cat:'materials', label:'Wriggling Worm',    emoji:'🪱', price:8,   rarity:'common',    desc:'Wiggly little guy' },
  { id:'pebble',    cat:'materials', label:'Smooth Pebble',     emoji:'🪨', price:10,  rarity:'common',    desc:'Nice to hold' },
  { id:'bone',      cat:'materials', label:'Old Bone',          emoji:'🦴', price:10,  rarity:'common',    desc:'Buried treasure' },
  { id:'leaf',      cat:'materials', label:'Fossil Leaf',       emoji:'🍂', price:12,  rarity:'common',    desc:'Ancient flora' },
  { id:'acorn',     cat:'materials', label:'Lucky Acorn',       emoji:'🌰', price:12,  rarity:'common',    desc:'Good luck charm' },
  { id:'mushroom',  cat:'materials', label:'Magic Mushroom',    emoji:'🍄', price:35,  rarity:'uncommon',  desc:'Magical properties' },
  { id:'crystal',   cat:'materials', label:'Blue Crystal',      emoji:'💎', price:40,  rarity:'uncommon',  desc:'Shimmers nicely' },
  { id:'fossil',    cat:'materials', label:'Tiny Fossil',       emoji:'🦕', price:50,  rarity:'uncommon',  desc:'Millions of years old' },
  { id:'bottle',    cat:'materials', label:'Message in Bottle', emoji:'🍶', price:55,  rarity:'uncommon',  desc:'What does it say?' },
  { id:'gem',       cat:'materials', label:'Ancient Gem',       emoji:'💍', price:120, rarity:'rare',      desc:'Priceless beauty' },
  { id:'crown',     cat:'materials', label:'Tiny Crown',        emoji:'👑', price:140, rarity:'rare',      desc:'Fit for royalty' },
  { id:'map',       cat:'materials', label:'Treasure Map',      emoji:'🗺️', price:130, rarity:'rare',      desc:'X marks the spot' },
  { id:'potion',    cat:'materials', label:'Mystery Potion',    emoji:'🧪', price:160, rarity:'rare',      desc:'Drink at your own risk' },
  { id:'star',      cat:'materials', label:'Fallen Star',       emoji:'⭐', price:400, rarity:'legendary', desc:'Fell from the sky' },
  { id:'fish_gold', cat:'materials', label:'Golden Fish',       emoji:'🐠', price:480, rarity:'legendary', desc:'Worth its weight in gold' },
  { id:'catbell',   cat:'materials', label:'Ancient Cat Bell',  emoji:'🔔', price:500, rarity:'legendary', desc:'Rings with mystery' },
];
module.exports = { SHOP_ITEMS };
